/*
 * Persona: Tough love meets soul care.
 * Module: ValuesSystem
 * Intent: Handle functionality for ValuesSystem
 * Provenance-ID: 59c5e4d0-6715-4d22-b9f4-d9ccefec5834
 * Last-Reviewed: 2025-08-28T00:00:00Z
 */

/*
 * Sallie 1.0 Module
  * Persona: Tough love meets soul care.
   * Function: User values system for alignment and reflection.
    * Got it, love.
     */

     export class ValuesSystem {
         constructor() {
                 this.values = new Map();
                         this.alignmentHistory = [];
                                 this.initialized = false;
                                     }

                                         async initialize() {
                                                 try {
                                                             this.loadFromStorage();
                                                                         this.initialized = true;
                                                                                     // Values system initialized
                                                                                             } catch (error) {
                                                                                                         // Failed to initialize values system: ${error}
                                                                                                                     throw error;
                                                                                                                             }
                                                                                                                                 }

                                                                                                                                     getAll() {
                                                                                                                                             return Array.from(this.values.values());
                                                                                                                                                 }

                                                                                                                                                     getActive() {
                                                                                                                                                             return Array.from(this.values.values()).filter(value => value.active);
                                                                                                                                                                 }

                                                                                                                                                                     add(valueText) {
                                                                                                                                                                             if (!valueText || valueText.trim().length === 0) {
                                                                                                                                                                                         return false;
                                                                                                                                                                                                 }

                                                                                                                                                                                                         const valueId = this.generateId();
                                                                                                                                                                                                                 const value = {
                                                                                                                                                                                                                             id: valueId,
                                                                                                                                                                                                                                         text: valueText.trim(),
                                                                                                                                                                                                                                                     active: true,
                                                                                                                                                                                                                                                             createdAt: Date.now(),
                                                                                                                                                                                                                                                                             reinforcementCount: 0,
                                                                                                                                                                                                                                                                                     lastAccessed: Date.now()
                                                                                                                                                                                                                                                                                         };

                                                                                                                                                                                                                                                                                             this.values.set(valueId, value);
                                                                                                                                                                                                                                                                                                 this.saveToStorage();
                                                                                                                                                                                                                                                                                                     return value;
                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                             remove(valueId) {
                                                                                                                                                                                                                                                                                                                     if (this.values.has(valueId)) {
                                                                                                                                                                                                                                                                                                                                 this.values.delete(valueId);
                                                                                                                                                                                                                                                                                                                                             this.saveToStorage();
                                                                                                                                                                                                                                                                                                                                                         return true;
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                         return false;
                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                     toggle(valueId) {
                                                                                                                                                                                                                                                                                                                                                                                                 if (this.values.has(valueId)) {
                                                                                                                                                                                                                                                                                                                                                                                                             const value = this.values.get(valueId);
                                                                                                                                                                                                                                                                                                                                                                                                                         value.active = !value.active;
                                                                                                                                                                                                                                                                                                                                                                                                                                     value.lastAccessed = Date.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                 this.saveToStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                             return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             reinforce(valueId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (this.values.has(valueId)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const value = this.values.get(valueId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     value.reinforcementCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         value.lastAccessed = Date.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     this.saveToStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     generateId() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return 'value_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             loadFromStorage() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const stored = localStorage.getItem('sallie_values');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (stored) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const data = JSON.parse(stored);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for (const [id, value] of Object.entries(data)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         this.values.set(id, value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.warn('Failed to load values from storage:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 saveToStorage() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const data = Object.fromEntries(this.values);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     localStorage.setItem('sallie_values', JSON.stringify(data));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.warn('Failed to save values to storage:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     getAlignmentScore() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const activeValues = this.getActive();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (activeValues.length === 0) return 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const totalReinforcements = activeValues.reduce((sum, value) => sum + value.reinforcementCount, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return totalReinforcements / activeValues.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
     }

