/*
 * Persona: Tough love meets soul care.
 * Module: FeatureRegistry
 * Intent: Handle functionality for FeatureRegistry
 * Provenance-ID: b283a549-f760-4d6e-9a68-1aa203c3f709
 * Last-Reviewed: 2025-08-28T00:00:00Z
 */

/*
 * Sallie 1.0 Module
  * Persona: Tough love meets soul care.
   * Function: Central registry for all Sallie features and metrics.
    * Got it, love.
     */

     export class FeatureRegistry {
         constructor() {
                 this.features = new Map();
                         this.metrics = new Map();
                                 this.initialized = false;
                                     }

                                         static instance = null;

                                             static getInstance() {
                                                     if (!FeatureRegistry.instance) {
                                                                 FeatureRegistry.instance = new FeatureRegistry();
                                                                         }
                                                                                 return FeatureRegistry.instance;
                                                                                     }

                                                                                         static register(name, implementation) {
                                                                                                 const registry = FeatureRegistry.getInstance();
                                                                                                         return registry.register(name, implementation);
                                                                                                             }

                                                                                                                 static get(name) {
                                                                                                                         const registry = FeatureRegistry.getInstance();
                                                                                                                                 return registry.get(name);
                                                                                                                                     }

                                                                                                                                         static recordUsage(featureName, executionTimeMs) {
                                                                                                                                                 const registry = FeatureRegistry.getInstance();
                                                                                                                                                         return registry.recordUsage(featureName, executionTimeMs);
                                                                                                                                                             }

                                                                                                                                                                 static getAllMetrics() {
                                                                                                                                                                         const registry = FeatureRegistry.getInstance();
                                                                                                                                                                                 return registry.getAllMetrics();
                                                                                                                                                                                     }

                                                                                                                                                                                         async initialize() {
                                                                                                                                                                                                 try {
                                                                                                                                                                                                         this.initialized = true;
                                                                                                                                                                                                                 console.log('Feature registry initialized');
                                                                                                                                                                                                                         } catch (error) {
                                                                                                                                                                                                                                         console.error('Failed to initialize feature registry:', error);
                                                                                                                                                                                                                                                         throw error;
                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                 }

                                                                                                                                                                                                     register(name, implementation) {
                                                                                                                                                                                                             if (!name || !implementation) {
                                                                                                                                                                                                                         throw new Error('Feature name and implementation are required');
                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                         this.features.set(name, {
                                                                                                                                                                                                                                                         name,
                                                                                                                                                                                                                                                                         implementation,
                                                                                                                                                                                                                                                                         registeredAt: Date.now(),
                                                                                                                                                                                                                                                                                         usageCount: 0,
                                                                                                                                                                                                                                                                                                         totalExecutionTime: 0
                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                         return true;
                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                 get(name) {
                                                                                                                                                                                                                                                                                                                                         return this.features.get(name);
                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                 recordUsage(featureName, executionTimeMs) {
                                                                                                                                                                                                                                                                                                                                                         if (this.features.has(featureName)) {
                                                                                                                                                                                                                                                                                                                                                                         const feature = this.features.get(featureName);
                                                                                                                                                                                                                                                                                                                                                                                                     feature.usageCount++;
                                                                                                                                                                                                                                                                                                                                                                                                         feature.totalExecutionTime += executionTimeMs;
                                                                                                                                                                                                                                                                                                                                                                                                                     feature.lastUsed = Date.now();

                                                                                                                                                                                                                                                                                                                                                                                                                                 // Record metrics
                                                                                                                                                                                                                                                                                                                                                                                                                                             const metrics = this.metrics.get(featureName) || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 metrics.push({
                                                                                                                                                                                                                                                                                                                                                                                                                 timestamp: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                 executionTime: executionTimeMs
                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 this.metrics.set(featureName, metrics);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             getAllMetrics() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const result = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for (const [name, feature] of this.features) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             result[name] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             usageCount: feature.usageCount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             averageExecutionTime: feature.usageCount > 0 ? feature.totalExecutionTime / feature.usageCount : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 lastUsed: feature.lastUsed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 metrics: this.metrics.get(name) || []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         getFeatureList() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return Array.from(this.features.keys());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             getUsageStats() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const totalFeatures = this.features.size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const activeFeatures = Array.from(this.features.values()).filter(f => f.usageCount > 0).length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const totalUsage = Array.from(this.features.values()).reduce((sum, f) => sum + f.usageCount, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             totalFeatures,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             activeFeatures,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             totalUsage,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 featureAdoptionRate: totalFeatures > 0 ? activeFeatures / totalFeatures : 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
     }

