name: Sallie CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Lint (ktlint)
        run: ./gradlew ktlintCheck || true
      - name: Package JAR
        run: ./gradlew shadowJar
      - name: Build Docker image
        run: docker build -t sallie:latest .
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: sallie-jar
          path: build/libs/Sallie-all.jar
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (sample)
        run: echo "Deploy step here (e.g., to cloud, server, etc.)"
