name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t sallie:latest .
      - name: Deploy to server
        run: echo "Add deployment steps here (e.g., to cloud, server, etc.)"
